# Generated by Django 3.2.4 on 2021-09-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user_address', models.CharField(blank=True, max_length=255, null=True)),
                ('endpoint', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
