version: "3.5"

services:
  # The Fast API/Django Hybrid Web App
  app:
    build: .
    image: &app app
    restart: unless-stopped
    command: bash -c "gunicorn --worker-class=uvicorn.workers.UvicornWorker --workers=5 --graceful-timeout=15 --timeout=20 app.asgi:app --log-level debug --bind 0.0.0.0:8000"
    env_file: &envfile
      - .env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./app:/home/app/web

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - app

  default_worker:
    build: .
    image: *app
    restart: unless-stopped
    env_file: *envfile
    command:
      [
        "celery",
        "--app=app.celery.app",
        "worker",
        "--concurrency=2",
        "--hostname=default_worker@%h",
        "--loglevel=INFO",
        "-E",
      ]
    volumes:
      - ./app:/home/app/web

  scheduler:
    build: .
    image: *app
    restart: unless-stopped
    env_file: *envfile
    command: bash -c "rm -f ./celerybeat-schedule && rm -f ./celerybeat.pid && celery -A app beat --loglevel=info"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./app:/home/app/web
    depends_on:
      - default_worker

  redis:
    restart: unless-stopped
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  static_volume:
