# Generated by Django 3.2.12 on 2022-02-15 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('block_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Txn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=255)),
                ('index', models.IntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quark.block')),
            ],
        ),
        migrations.AddIndex(
            model_name='eventname',
            index=models.Index(fields=['event_name'], name='quark_event_event_n_75bc3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventname',
            unique_together={('event_name',)},
        ),
        migrations.AddIndex(
            model_name='environment',
            index=models.Index(fields=['environment'], name='quark_envir_environ_2c518a_idx'),
        ),
        migrations.AddField(
            model_name='contract',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quark.environment'),
        ),
        migrations.AddField(
            model_name='block',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quark.environment'),
        ),
        migrations.AddIndex(
            model_name='txn',
            index=models.Index(fields=['hash'], name='quark_txn_hash_8877ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='txn',
            unique_together={('index', 'block'), ('hash', 'block')},
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['address'], name='quark_contr_address_0755c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('address',)},
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['block_number'], name='quark_block_block_n_a30b97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('environment', 'block_number')},
        ),
    ]
